theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: false  
  logo:
    header: "/assets/images/mouvess.png"
    footer: "/assets/images/mouvess-complet.png"
  breadcrumb:
    position: after-hero
